-- 0004 — el precio pasa a salir de la ENTREGA, de 011-precio-por-entrega.
--
-- El cliente definio sus zonas y sus precios por adonde va el paquete; el sitio
-- venia cobrando por la zona del RETIRO. Ver
-- docs/decisions/pricing-from-delivery-zone.md, que enmienda el Principio V de
-- la constitucion por segunda vez (3.0.0 -> 4.0.0), y
-- specs/011-precio-por-entrega/data-model.md para el porque de cada linea.
--
-- Solo hacia adelante: no hay migracion de vuelta, igual que 0001 y 0003.

-- --------------------------------------------------------------------------
-- 1. El punto de entrega, que es el que ahora decide zona y precio.
-- --------------------------------------------------------------------------
--
-- **NULLABLE, y la primera version de esta migracion no lo era.**
--
-- Entraba como `NOT NULL` sin default, apoyandose en que produccion estaba
-- vacia. **No lo estaba**: el 2026-08-23 el despliegue tumbo el servicio con
--
--     ERROR: column "entrega_punto" of relation "pedidos" contains null values
--
-- y el backend quedo sin arrancar hasta que se corrigio esto. La migracion corre
-- en una transaccion, asi que no dejo nada a medias, pero el servicio reintenta
-- al arrancar y no puede pasar de aca.
--
-- Por que nullable y no un relleno: **los pedidos anteriores a `011` no tienen
-- punto de entrega y no se puede inventar uno**. Un default seria un punto
-- falso, o sea un precio falso, en filas que nadie reviso.
--
-- **La regla no se afloja donde importa.** Que un pedido NUEVO no pueda existir
-- sin punto de entrega lo sostienen las dos guardas del servicio
-- (`handlers.go` y `pedido.go`), no la columna; lo que se pierde es la garantia
-- a nivel base sobre las filas viejas, que es justamente donde no puede haberla.
-- Un `entrega_punto` nulo significa "pedido anterior al cambio de precios", y
-- `web/components/pedido/crear-pedido.tsx` ya lo trata como tal (FR-013).
ALTER TABLE pedidos
    ADD COLUMN entrega_punto geography(Point, 4326);

-- --------------------------------------------------------------------------
-- 2. El punto de retiro deja de ser obligatorio.
-- --------------------------------------------------------------------------
--
-- **El comentario de 0003 sobre esta columna quedo falso.** Decia, textual:
--
--     "NOT NULL: sin punto no hay zona, sin zona no hay precio, y sin precio no
--      hay pedido. Es tambien lo que mantiene el precio RECALCULABLE despues."
--
-- Ese argumento ahora describe a entrega_punto, no a esta. **0003 no se edita**
-- —es una migracion ya aplicada, y reescribirla es reescribir historia que otra
-- base ya ejecuto—, asi que la correccion vive aca.
--
-- Que hace el punto de retiro a partir de ahora, y por que se guarda igual:
--
--   1. Comprueba que el retiro caiga dentro del area de servicio (FR-011). Es
--      una comprobacion de MEJOR ESFUERZO: solo actua cuando el texto resuelve.
--   2. Le da coordenadas reales a la ruta que la app Android va a planificar.
--
-- Y por que puede faltar: cuando el texto del retiro no resuelve a ningun cruce
-- —calle fuera del indice, error de tipeo— o cuando la calle es HOMONIMA y hay
-- varios candidatos, el pedido se guarda igual, sin punto y sin decirle nada a
-- quien lo crea (FR-014, FR-015). Una fila con retiro_punto NULL no es un error:
-- es ese caso, y `WHERE retiro_punto IS NULL` es como se lo encuentra.
--
-- **La app Android tiene que tolerar un retiro sin coordenadas.**
ALTER TABLE pedidos
    ALTER COLUMN retiro_punto DROP NOT NULL;
